#ifndef EGL_EGLCONFIG_DEFS_H
#define EGL_EGLCONFIG_DEFS_H

#include <stdint.h>
#include "EGL/egl.h"

#define EGL_NO_CONFIG EGL_NON_CONFORMANT_CONFIG

namespace EGL
{

namespace Config
{

static int egl_config_defs_array[] = {
				8,	EGL_RED_SIZE,
				8,	EGL_GREEN_SIZE,
				8,	EGL_BLUE_SIZE,
				8,	EGL_ALPHA_SIZE,
				24,	EGL_DEPTH_SIZE,
				0,	EGL_STENCIL_SIZE,
				EGL_WINDOW_BIT, EGL_SURFACE_TYPE,
				0, EGL_NATIVE_VISUAL_ID,
				EGL_NONE, EGL_NONE,
				
				8,	EGL_RED_SIZE,
				8,	EGL_GREEN_SIZE,
				8,	EGL_BLUE_SIZE,
				0,	EGL_ALPHA_SIZE,
				24,	EGL_DEPTH_SIZE,
				0,	EGL_STENCIL_SIZE,
				EGL_WINDOW_BIT, EGL_SURFACE_TYPE,
				0, EGL_NATIVE_VISUAL_ID,
				EGL_NONE, EGL_NONE,
				
				8,	EGL_RED_SIZE,
				8,	EGL_GREEN_SIZE,
				0,	EGL_BLUE_SIZE,
				0,	EGL_ALPHA_SIZE,
				24,	EGL_DEPTH_SIZE,
				0,	EGL_STENCIL_SIZE,
				EGL_WINDOW_BIT, EGL_SURFACE_TYPE,
				0, EGL_NATIVE_VISUAL_ID,
				EGL_NONE, EGL_NONE,
				
				8,	EGL_RED_SIZE,
				0,	EGL_GREEN_SIZE,
				0,	EGL_BLUE_SIZE,
				0,	EGL_ALPHA_SIZE,
				24,	EGL_DEPTH_SIZE,
				0,	EGL_STENCIL_SIZE,
				EGL_WINDOW_BIT, EGL_SURFACE_TYPE,
				0, EGL_NATIVE_VISUAL_ID,
				EGL_NONE, EGL_NONE,
				
				8,	EGL_RED_SIZE,
				8,	EGL_GREEN_SIZE,
				8,	EGL_BLUE_SIZE,
				8,	EGL_ALPHA_SIZE,
				24,	EGL_DEPTH_SIZE,
				8,	EGL_STENCIL_SIZE,
				EGL_WINDOW_BIT, EGL_SURFACE_TYPE,
				0, EGL_NATIVE_VISUAL_ID,
				EGL_NONE, EGL_NONE,
				
				8,	EGL_RED_SIZE,
				8,	EGL_GREEN_SIZE,
				8,	EGL_BLUE_SIZE,
				0,	EGL_ALPHA_SIZE,
				24,	EGL_DEPTH_SIZE,
				8,	EGL_STENCIL_SIZE,
				EGL_WINDOW_BIT, EGL_SURFACE_TYPE,
				0, EGL_NATIVE_VISUAL_ID,
				EGL_NONE, EGL_NONE,
				
				8,	EGL_RED_SIZE,
				8,	EGL_GREEN_SIZE,
				0,	EGL_BLUE_SIZE,
				0,	EGL_ALPHA_SIZE,
				24,	EGL_DEPTH_SIZE,
				8,	EGL_STENCIL_SIZE,
				EGL_WINDOW_BIT, EGL_SURFACE_TYPE,
				0, EGL_NATIVE_VISUAL_ID,
				EGL_NONE, EGL_NONE,
				
				8,	EGL_RED_SIZE,
				0,	EGL_GREEN_SIZE,
				0,	EGL_BLUE_SIZE,
				0,	EGL_ALPHA_SIZE,
				24,	EGL_DEPTH_SIZE,
				8,	EGL_STENCIL_SIZE,
				EGL_WINDOW_BIT, EGL_SURFACE_TYPE,
				0, EGL_NATIVE_VISUAL_ID,
				EGL_NONE, EGL_NONE,
				
				EGL_NO_CONFIG, EGL_NO_CONFIG,//end of all
};

}//namespace Config

}//namespace EGL


#endif //EGL_EGLCONFIG_DEFS_H