name: Android
on: [push]
jobs:
  build:
    name: NDK-R21e
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Android NDK R23
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
    - uses: actions/checkout@v2
    - name: build
      run: |
        ndk-build
