name: Android
on: [push]
jobs:
  build:
    name: NDK-R21e
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Android NDK R23
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
    - uses: actions/checkout@v2
    - name: build
      run: |
        $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APP_APPLICATION_MK=./Application.mk
